// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YuFoot.EntitiesContext.Migrations
{
    /// <inheritdoc />
    public partial class Added_Link_GamePlayed_FifaTeam : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 13, 19, 18, 55, 466, DateTimeKind.Local).AddTicks(8740),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 13, 18, 16, 35, 593, DateTimeKind.Local).AddTicks(9390));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "GamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 13, 19, 18, 55, 466, DateTimeKind.Local).AddTicks(7690),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 13, 18, 16, 35, 593, DateTimeKind.Local).AddTicks(8480));

            migrationBuilder.AddColumn<int>(
                name: "team_1_id",
                table: "GamePlayed",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "team_2_id",
                table: "GamePlayed",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_GamePlayed_team_1_id",
                table: "GamePlayed",
                column: "team_1_id");

            migrationBuilder.CreateIndex(
                name: "IX_GamePlayed_team_2_id",
                table: "GamePlayed",
                column: "team_2_id");

            migrationBuilder.AddForeignKey(
                name: "FK_FifaTeam_GamePlayed_Team1",
                table: "GamePlayed",
                column: "team_1_id",
                principalTable: "FifaTeam",
                principalColumn: "id");

            migrationBuilder.AddForeignKey(
                name: "FK_FifaTeam_GamePlayed_Team2",
                table: "GamePlayed",
                column: "team_2_id",
                principalTable: "FifaTeam",
                principalColumn: "id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_FifaTeam_GamePlayed_Team1",
                table: "GamePlayed");

            migrationBuilder.DropForeignKey(
                name: "FK_FifaTeam_GamePlayed_Team2",
                table: "GamePlayed");

            migrationBuilder.DropIndex(
                name: "IX_GamePlayed_team_1_id",
                table: "GamePlayed");

            migrationBuilder.DropIndex(
                name: "IX_GamePlayed_team_2_id",
                table: "GamePlayed");

            migrationBuilder.DropColumn(
                name: "team_1_id",
                table: "GamePlayed");

            migrationBuilder.DropColumn(
                name: "team_2_id",
                table: "GamePlayed");

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 13, 18, 16, 35, 593, DateTimeKind.Local).AddTicks(9390),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 13, 19, 18, 55, 466, DateTimeKind.Local).AddTicks(8740));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "GamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 13, 18, 16, 35, 593, DateTimeKind.Local).AddTicks(8480),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 13, 19, 18, 55, 466, DateTimeKind.Local).AddTicks(7690));
        }
    }
}
