// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YuGames.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Added_Missing_Foreign_Key : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "joined_at",
                table: "TournamentPlayer",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 14, 20, 21, 57, 371, DateTimeKind.Utc).AddTicks(4352),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 14, 20, 13, 38, 116, DateTimeKind.Utc).AddTicks(8546));

            migrationBuilder.AddColumn<int>(
                name: "tournament_id",
                table: "TournamentPlayer",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_to",
                table: "Tournament",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 15, 20, 21, 57, 371, DateTimeKind.Utc).AddTicks(3810),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 15, 20, 13, 38, 116, DateTimeKind.Utc).AddTicks(8099));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_from",
                table: "Tournament",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 14, 20, 21, 57, 371, DateTimeKind.Utc).AddTicks(3699),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 14, 20, 13, 38, 116, DateTimeKind.Utc).AddTicks(7983));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 14, 20, 21, 57, 371, DateTimeKind.Utc).AddTicks(8152),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 14, 20, 13, 38, 117, DateTimeKind.Utc).AddTicks(1220));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 14, 22, 21, 57, 371, DateTimeKind.Local).AddTicks(9047),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 14, 22, 13, 38, 117, DateTimeKind.Local).AddTicks(2070));

            migrationBuilder.CreateIndex(
                name: "IX_TournamentPlayer_tournament_id",
                table: "TournamentPlayer",
                column: "tournament_id");

            migrationBuilder.AddForeignKey(
                name: "FK_TournamentPlayer_Tournament",
                table: "TournamentPlayer",
                column: "tournament_id",
                principalTable: "Tournament",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TournamentPlayer_Tournament",
                table: "TournamentPlayer");

            migrationBuilder.DropIndex(
                name: "IX_TournamentPlayer_tournament_id",
                table: "TournamentPlayer");

            migrationBuilder.DropColumn(
                name: "tournament_id",
                table: "TournamentPlayer");

            migrationBuilder.AlterColumn<DateTime>(
                name: "joined_at",
                table: "TournamentPlayer",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 14, 20, 13, 38, 116, DateTimeKind.Utc).AddTicks(8546),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 14, 20, 21, 57, 371, DateTimeKind.Utc).AddTicks(4352));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_to",
                table: "Tournament",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 15, 20, 13, 38, 116, DateTimeKind.Utc).AddTicks(8099),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 15, 20, 21, 57, 371, DateTimeKind.Utc).AddTicks(3810));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_from",
                table: "Tournament",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 14, 20, 13, 38, 116, DateTimeKind.Utc).AddTicks(7983),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 14, 20, 21, 57, 371, DateTimeKind.Utc).AddTicks(3699));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 14, 20, 13, 38, 117, DateTimeKind.Utc).AddTicks(1220),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 14, 20, 21, 57, 371, DateTimeKind.Utc).AddTicks(8152));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 14, 22, 13, 38, 117, DateTimeKind.Local).AddTicks(2070),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 14, 22, 21, 57, 371, DateTimeKind.Local).AddTicks(9047));
        }
    }
}
