// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YuGames.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class First_Version : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FifaTeam",
                columns: table => new
                {
                    id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    name = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FifaTeam", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "Platform",
                columns: table => new
                {
                    id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    name = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Platform", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "Player",
                columns: table => new
                {
                    id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    keycloak_id = table.Column<string>(type: "TEXT", maxLength: 50, nullable: true),
                    full_name = table.Column<string>(type: "TEXT", maxLength: 100, nullable: true),
                    nickname = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    profile_picture_url = table.Column<string>(type: "TEXT", maxLength: 500, nullable: true),
                    created_on = table.Column<DateTime>(type: "TEXT", nullable: false, defaultValue: new DateTime(2023, 8, 19, 16, 22, 11, 777, DateTimeKind.Utc).AddTicks(9521))
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Player", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "FifaGamePlayed",
                columns: table => new
                {
                    id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    played_on = table.Column<DateTime>(type: "TEXT", nullable: false, defaultValue: new DateTime(2023, 8, 19, 18, 22, 11, 778, DateTimeKind.Local).AddTicks(276)),
                    team_code_1 = table.Column<string>(type: "TEXT", maxLength: 10, nullable: true),
                    team_1_id = table.Column<int>(type: "INTEGER", nullable: true),
                    team_2_id = table.Column<int>(type: "INTEGER", nullable: true),
                    team_code_2 = table.Column<string>(type: "TEXT", maxLength: 10, nullable: true),
                    team_score_1 = table.Column<int>(type: "INTEGER", maxLength: 100, nullable: false, defaultValue: 0),
                    team_score_2 = table.Column<int>(type: "INTEGER", maxLength: 100, nullable: false, defaultValue: 0),
                    platform_id = table.Column<int>(type: "INTEGER", nullable: false),
                    created_by_id = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FifaGamePlayed", x => x.id);
                    table.ForeignKey(
                        name: "FK_FifaGamePlayed_FifaTeam1",
                        column: x => x.team_1_id,
                        principalTable: "FifaTeam",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_FifaGamePlayed_FifaTeam2",
                        column: x => x.team_2_id,
                        principalTable: "FifaTeam",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_FifaGamePlayed_Platform",
                        column: x => x.platform_id,
                        principalTable: "Platform",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_FifaGamePlayed_Player_Created_By",
                        column: x => x.created_by_id,
                        principalTable: "Player",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "FifaTeamPlayer",
                columns: table => new
                {
                    id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    player_id = table.Column<int>(type: "INTEGER", nullable: false),
                    fifa_game_id = table.Column<int>(type: "INTEGER", nullable: false),
                    team = table.Column<int>(type: "INTEGER", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FifaTeamPlayer", x => x.id);
                    table.ForeignKey(
                        name: "FK_FifaTeamPlayer_FifaGamePlayed",
                        column: x => x.fifa_game_id,
                        principalTable: "FifaGamePlayed",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_FifaTeamPlayer_Player",
                        column: x => x.player_id,
                        principalTable: "Player",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Highlight",
                columns: table => new
                {
                    id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    name = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    description = table.Column<string>(type: "TEXT", maxLength: 500, nullable: true),
                    created_by_id = table.Column<int>(type: "INTEGER", nullable: false),
                    fifa_game_id = table.Column<int>(type: "INTEGER", nullable: false),
                    external_url = table.Column<string>(type: "TEXT", maxLength: 3000, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Highlight", x => x.id);
                    table.ForeignKey(
                        name: "FK_FifaGame_Highlight",
                        column: x => x.fifa_game_id,
                        principalTable: "FifaGamePlayed",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Highlight_Player_Created_By",
                        column: x => x.created_by_id,
                        principalTable: "Player",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_FifaGamePlayed_created_by_id",
                table: "FifaGamePlayed",
                column: "created_by_id");

            migrationBuilder.CreateIndex(
                name: "IX_FifaGamePlayed_platform_id",
                table: "FifaGamePlayed",
                column: "platform_id");

            migrationBuilder.CreateIndex(
                name: "IX_FifaGamePlayed_team_1_id",
                table: "FifaGamePlayed",
                column: "team_1_id");

            migrationBuilder.CreateIndex(
                name: "IX_FifaGamePlayed_team_2_id",
                table: "FifaGamePlayed",
                column: "team_2_id");

            migrationBuilder.CreateIndex(
                name: "IX_FifaTeamPlayer_fifa_game_id",
                table: "FifaTeamPlayer",
                column: "fifa_game_id");

            migrationBuilder.CreateIndex(
                name: "IX_FifaTeamPlayer_player_id",
                table: "FifaTeamPlayer",
                column: "player_id");

            migrationBuilder.CreateIndex(
                name: "IX_Highlight_created_by_id",
                table: "Highlight",
                column: "created_by_id");

            migrationBuilder.CreateIndex(
                name: "IX_Highlight_fifa_game_id",
                table: "Highlight",
                column: "fifa_game_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FifaTeamPlayer");

            migrationBuilder.DropTable(
                name: "Highlight");

            migrationBuilder.DropTable(
                name: "FifaGamePlayed");

            migrationBuilder.DropTable(
                name: "FifaTeam");

            migrationBuilder.DropTable(
                name: "Platform");

            migrationBuilder.DropTable(
                name: "Player");
        }
    }
}
