// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YuFoot.Repository.Migrations
{
    /// <inheritdoc />
    public partial class Added_Highlights : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 2, 20, 50, 9, 750, DateTimeKind.Local).AddTicks(6291),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 2, 20, 33, 19, 57, DateTimeKind.Local).AddTicks(7568));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "GamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 2, 20, 50, 9, 750, DateTimeKind.Local).AddTicks(4548),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 2, 20, 33, 19, 57, DateTimeKind.Local).AddTicks(5418));

            migrationBuilder.CreateTable(
                name: "Highlight",
                columns: table => new
                {
                    id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    name = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    CreatedById = table.Column<int>(type: "INTEGER", nullable: false),
                    GameId = table.Column<int>(type: "INTEGER", nullable: false),
                    external_url = table.Column<string>(type: "TEXT", maxLength: 3000, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Highlight", x => x.id);
                    table.ForeignKey(
                        name: "FK_Highlight_GamePlayed",
                        column: x => x.GameId,
                        principalTable: "GamePlayed",
                        principalColumn: "id");
                    table.ForeignKey(
                        name: "FK_Highlight_Player",
                        column: x => x.CreatedById,
                        principalTable: "Player",
                        principalColumn: "id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_Highlight_CreatedById",
                table: "Highlight",
                column: "CreatedById");

            migrationBuilder.CreateIndex(
                name: "IX_Highlight_GameId",
                table: "Highlight",
                column: "GameId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Highlight");

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 2, 20, 33, 19, 57, DateTimeKind.Local).AddTicks(7568),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 2, 20, 50, 9, 750, DateTimeKind.Local).AddTicks(6291));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "GamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 2, 20, 33, 19, 57, DateTimeKind.Local).AddTicks(5418),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 2, 20, 50, 9, 750, DateTimeKind.Local).AddTicks(4548));
        }
    }
}
