// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YuFoot.Repository.Migrations
{
    /// <inheritdoc />
    public partial class Added_CreatedBy_on_GamePlayed : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 6, 14, 11, 8, 753, DateTimeKind.Local).AddTicks(5219),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 5, 2, 28, 56, 180, DateTimeKind.Local).AddTicks(9513));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "GamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 6, 14, 11, 8, 753, DateTimeKind.Local).AddTicks(3596),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 5, 2, 28, 56, 180, DateTimeKind.Local).AddTicks(7890));

            migrationBuilder.AddColumn<int>(
                name: "CreatedById",
                table: "GamePlayed",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "IX_GamePlayed_CreatedById",
                table: "GamePlayed",
                column: "CreatedById");

            migrationBuilder.AddForeignKey(
                name: "FK_GamePlayed_CreatedBy",
                table: "GamePlayed",
                column: "CreatedById",
                principalTable: "Player",
                principalColumn: "id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_GamePlayed_CreatedBy",
                table: "GamePlayed");

            migrationBuilder.DropIndex(
                name: "IX_GamePlayed_CreatedById",
                table: "GamePlayed");

            migrationBuilder.DropColumn(
                name: "CreatedById",
                table: "GamePlayed");

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 5, 2, 28, 56, 180, DateTimeKind.Local).AddTicks(9513),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 6, 14, 11, 8, 753, DateTimeKind.Local).AddTicks(5219));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "GamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 8, 5, 2, 28, 56, 180, DateTimeKind.Local).AddTicks(7890),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 8, 6, 14, 11, 8, 753, DateTimeKind.Local).AddTicks(3596));
        }
    }
}
