// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameOn.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Added_FifaGamePlayed_Season_Link : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 12, 11, 9, 42, 497, DateTimeKind.Utc).AddTicks(9950),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 12, 9, 22, 7, 180, DateTimeKind.Utc).AddTicks(150));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 12, 13, 9, 42, 498, DateTimeKind.Local).AddTicks(470),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 12, 11, 22, 7, 180, DateTimeKind.Local).AddTicks(760));

            migrationBuilder.AddColumn<int>(
                name: "season_id",
                table: "FifaGamePlayed",
                type: "INTEGER",
                nullable: false,
                defaultValue: 1);

            migrationBuilder.CreateIndex(
                name: "IX_FifaGamePlayed_season_id",
                table: "FifaGamePlayed",
                column: "season_id");

            migrationBuilder.AddForeignKey(
                name: "FK_FifaGamePlayed_Season",
                table: "FifaGamePlayed",
                column: "season_id",
                principalTable: "Season",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_FifaGamePlayed_Season",
                table: "FifaGamePlayed");

            migrationBuilder.DropIndex(
                name: "IX_FifaGamePlayed_season_id",
                table: "FifaGamePlayed");

            migrationBuilder.DropColumn(
                name: "season_id",
                table: "FifaGamePlayed");

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 12, 9, 22, 7, 180, DateTimeKind.Utc).AddTicks(150),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 12, 11, 9, 42, 497, DateTimeKind.Utc).AddTicks(9950));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(2023, 9, 12, 11, 22, 7, 180, DateTimeKind.Local).AddTicks(760),
                oldClrType: typeof(DateTime),
                oldType: "TEXT",
                oldDefaultValue: new DateTime(2023, 9, 12, 13, 9, 42, 498, DateTimeKind.Local).AddTicks(470));
        }
    }
}
