// <auto-generated />

using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameOn.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Added_SoccerFive_VoteAnswers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "joined_at",
                table: "TournamentPlayer",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 9, 5, 9, 142, DateTimeKind.Utc).AddTicks(6572),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(6147));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_to",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 10, 9, 5, 9, 142, DateTimeKind.Utc).AddTicks(4731),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 10, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(4577));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_from",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 9, 5, 9, 142, DateTimeKind.Utc).AddTicks(4476),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(4239));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 9, 5, 9, 142, DateTimeKind.Utc).AddTicks(3031),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(2094));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 11, 5, 9, 143, DateTimeKind.Local).AddTicks(2067),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 10, 57, 42, 801, DateTimeKind.Local).AddTicks(1247));

            migrationBuilder.CreateTable(
                name: "SoccerFiveVoteAnswer",
                columns: table => new
                {
                    id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    vote_choice_id = table.Column<int>(type: "int", nullable: false),
                    player_id = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SoccerFiveVoteAnswer", x => x.id);
                    table.ForeignKey(
                        name: "FK_Player_VoteAnswer",
                        column: x => x.player_id,
                        principalTable: "Player",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_VoteChoice_VoteAnswer",
                        column: x => x.vote_choice_id,
                        principalTable: "SoccerFiveVoteChoice",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateIndex(
                name: "IX_SoccerFiveVoteAnswer_player_id",
                table: "SoccerFiveVoteAnswer",
                column: "player_id");

            migrationBuilder.CreateIndex(
                name: "IX_SoccerFiveVoteAnswer_vote_choice_id",
                table: "SoccerFiveVoteAnswer",
                column: "vote_choice_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SoccerFiveVoteAnswer");

            migrationBuilder.AlterColumn<DateTime>(
                name: "joined_at",
                table: "TournamentPlayer",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(6147),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 9, 5, 9, 142, DateTimeKind.Utc).AddTicks(6572));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_to",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 10, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(4577),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 10, 9, 5, 9, 142, DateTimeKind.Utc).AddTicks(4731));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_from",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(4239),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 9, 5, 9, 142, DateTimeKind.Utc).AddTicks(4476));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(2094),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 9, 5, 9, 142, DateTimeKind.Utc).AddTicks(3031));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 10, 57, 42, 801, DateTimeKind.Local).AddTicks(1247),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 11, 5, 9, 143, DateTimeKind.Local).AddTicks(2067));
        }
    }
}
