// <auto-generated />

using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameOn.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Added_SoccerFive_VoteChoices : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "joined_at",
                table: "TournamentPlayer",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(6147),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 40, 26, 936, DateTimeKind.Utc).AddTicks(3815));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_to",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 10, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(4577),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 10, 8, 40, 26, 936, DateTimeKind.Utc).AddTicks(1856));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_from",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(4239),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 40, 26, 936, DateTimeKind.Utc).AddTicks(1542));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(2094),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 40, 26, 935, DateTimeKind.Utc).AddTicks(9839));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 10, 57, 42, 801, DateTimeKind.Local).AddTicks(1247),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 10, 40, 26, 936, DateTimeKind.Local).AddTicks(8838));

            migrationBuilder.CreateTable(
                name: "SoccerFiveVoteChoice",
                columns: table => new
                {
                    id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    soccer_five_id = table.Column<int>(type: "int", nullable: false),
                    label = table.Column<string>(type: "varchar(100)", maxLength: 100, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    order = table.Column<int>(type: "int", nullable: false, defaultValue: 1)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SoccerFiveVoteChoice", x => x.id);
                    table.ForeignKey(
                        name: "FK_SoccerFive_VoteChoice",
                        column: x => x.soccer_five_id,
                        principalTable: "SoccerFive",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateIndex(
                name: "IX_SoccerFiveVoteChoice_soccer_five_id",
                table: "SoccerFiveVoteChoice",
                column: "soccer_five_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SoccerFiveVoteChoice");

            migrationBuilder.AlterColumn<DateTime>(
                name: "joined_at",
                table: "TournamentPlayer",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 40, 26, 936, DateTimeKind.Utc).AddTicks(3815),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(6147));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_to",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 10, 8, 40, 26, 936, DateTimeKind.Utc).AddTicks(1856),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 10, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(4577));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_from",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 40, 26, 936, DateTimeKind.Utc).AddTicks(1542),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(4239));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 8, 40, 26, 935, DateTimeKind.Utc).AddTicks(9839),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 8, 57, 42, 800, DateTimeKind.Utc).AddTicks(2094));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2024, 8, 9, 10, 40, 26, 936, DateTimeKind.Local).AddTicks(8838),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2024, 8, 9, 10, 57, 42, 801, DateTimeKind.Local).AddTicks(1247));
        }
    }
}
