// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameOn.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Reworked_LolGameParticipant_Relations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Player_LoL_Game_Participant",
                table: "LeagueOfLegendsGameParticipant");

            migrationBuilder.AddForeignKey(
                name: "FK_Player_LoL_Game_Participant",
                table: "LeagueOfLegendsGameParticipant",
                column: "player_id",
                principalTable: "Player",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Player_LoL_Game_Participant",
                table: "LeagueOfLegendsGameParticipant");

            migrationBuilder.AddForeignKey(
                name: "FK_Player_LoL_Game_Participant",
                table: "LeagueOfLegendsGameParticipant",
                column: "player_id",
                principalTable: "Player",
                principalColumn: "id");
        }
    }
}
