// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameOn.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Updated_Column_Name : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "ChampLevel",
                table: "LeagueOfLegendsGameParticipant",
                newName: "champLevel");

            migrationBuilder.RenameColumn(
                name: "Assists",
                table: "LeagueOfLegendsGameParticipant",
                newName: "assists");

            migrationBuilder.AlterColumn<DateTime>(
                name: "joined_at",
                table: "TournamentPlayer",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 21, 19, 23, 520, DateTimeKind.Utc).AddTicks(2399),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 21, 6, 41, 892, DateTimeKind.Utc).AddTicks(7644));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_to",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 26, 21, 19, 23, 517, DateTimeKind.Utc).AddTicks(3164),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 26, 21, 6, 41, 889, DateTimeKind.Utc).AddTicks(5552));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_from",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 21, 19, 23, 517, DateTimeKind.Utc).AddTicks(2644),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 21, 6, 41, 889, DateTimeKind.Utc).AddTicks(4854));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 21, 19, 23, 514, DateTimeKind.Utc).AddTicks(2987),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 21, 6, 41, 886, DateTimeKind.Utc).AddTicks(2844));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "LeagueOfLegendsRankHistory",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 534, DateTimeKind.Local).AddTicks(2932),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 906, DateTimeKind.Local).AddTicks(3077));

            migrationBuilder.AddColumn<int>(
                name: "deaths",
                table: "LeagueOfLegendsGameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "kills",
                table: "LeagueOfLegendsGameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<DateTime>(
                name: "retrieved_on",
                table: "LeagueOfLegendsGame",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 535, DateTimeKind.Local).AddTicks(8636),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 907, DateTimeKind.Local).AddTicks(6871));

            migrationBuilder.AlterColumn<DateTime>(
                name: "game_start",
                table: "LeagueOfLegendsGame",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 535, DateTimeKind.Local).AddTicks(8872),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 907, DateTimeKind.Local).AddTicks(7073));

            migrationBuilder.AlterColumn<DateTime>(
                name: "game_end",
                table: "LeagueOfLegendsGame",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 535, DateTimeKind.Local).AddTicks(9008),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 907, DateTimeKind.Local).AddTicks(7244));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 523, DateTimeKind.Local).AddTicks(1088),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 895, DateTimeKind.Local).AddTicks(6771));

            migrationBuilder.AlterColumn<DateTime>(
                name: "publication_date",
                table: "Changelog",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 533, DateTimeKind.Local).AddTicks(2074),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 905, DateTimeKind.Local).AddTicks(5379));
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "deaths",
                table: "LeagueOfLegendsGameParticipant");

            migrationBuilder.DropColumn(
                name: "kills",
                table: "LeagueOfLegendsGameParticipant");

            migrationBuilder.RenameColumn(
                name: "champLevel",
                table: "LeagueOfLegendsGameParticipant",
                newName: "ChampLevel");

            migrationBuilder.RenameColumn(
                name: "assists",
                table: "LeagueOfLegendsGameParticipant",
                newName: "Assists");

            migrationBuilder.AlterColumn<DateTime>(
                name: "joined_at",
                table: "TournamentPlayer",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 21, 6, 41, 892, DateTimeKind.Utc).AddTicks(7644),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 21, 19, 23, 520, DateTimeKind.Utc).AddTicks(2399));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_to",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 26, 21, 6, 41, 889, DateTimeKind.Utc).AddTicks(5552),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 26, 21, 19, 23, 517, DateTimeKind.Utc).AddTicks(3164));

            migrationBuilder.AlterColumn<DateTime>(
                name: "planned_from",
                table: "Tournament",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 21, 6, 41, 889, DateTimeKind.Utc).AddTicks(4854),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 21, 19, 23, 517, DateTimeKind.Utc).AddTicks(2644));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "Player",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 21, 6, 41, 886, DateTimeKind.Utc).AddTicks(2844),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 21, 19, 23, 514, DateTimeKind.Utc).AddTicks(2987));

            migrationBuilder.AlterColumn<DateTime>(
                name: "created_on",
                table: "LeagueOfLegendsRankHistory",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 906, DateTimeKind.Local).AddTicks(3077),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 534, DateTimeKind.Local).AddTicks(2932));

            migrationBuilder.AlterColumn<DateTime>(
                name: "retrieved_on",
                table: "LeagueOfLegendsGame",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 907, DateTimeKind.Local).AddTicks(6871),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 535, DateTimeKind.Local).AddTicks(8636));

            migrationBuilder.AlterColumn<DateTime>(
                name: "game_start",
                table: "LeagueOfLegendsGame",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 907, DateTimeKind.Local).AddTicks(7073),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 535, DateTimeKind.Local).AddTicks(8872));

            migrationBuilder.AlterColumn<DateTime>(
                name: "game_end",
                table: "LeagueOfLegendsGame",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 907, DateTimeKind.Local).AddTicks(7244),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 535, DateTimeKind.Local).AddTicks(9008));

            migrationBuilder.AlterColumn<DateTime>(
                name: "played_on",
                table: "FifaGamePlayed",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 895, DateTimeKind.Local).AddTicks(6771),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 523, DateTimeKind.Local).AddTicks(1088));

            migrationBuilder.AlterColumn<DateTime>(
                name: "publication_date",
                table: "Changelog",
                type: "datetime(6)",
                nullable: false,
                defaultValue: new DateTime(2025, 1, 25, 22, 6, 41, 905, DateTimeKind.Local).AddTicks(5379),
                oldClrType: typeof(DateTime),
                oldType: "datetime(6)",
                oldDefaultValue: new DateTime(2025, 1, 25, 22, 19, 23, 533, DateTimeKind.Local).AddTicks(2074));
        }
    }
}
