// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameOn.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Added_Damage_History_in_LoL_Game_Timeline : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "magic_damage_done",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "magic_damage_done_to_champions",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "magic_damage_taken",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "physical_damage_done",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "physical_damage_done_to_champions",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "physical_damage_taken",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "total_damage_done",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "total_damage_done_to_champions",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "total_damage_taken",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "true_damage_done",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "true_damage_done_to_champions",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "true_damage_taken",
                table: "LeagueOfLegendsGameTimelineFrameParticipant",
                type: "int",
                nullable: false,
                defaultValue: 0);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "magic_damage_done",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "magic_damage_done_to_champions",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "magic_damage_taken",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "physical_damage_done",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "physical_damage_done_to_champions",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "physical_damage_taken",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "total_damage_done",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "total_damage_done_to_champions",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "total_damage_taken",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "true_damage_done",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "true_damage_done_to_champions",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");

            migrationBuilder.DropColumn(
                name: "true_damage_taken",
                table: "LeagueOfLegendsGameTimelineFrameParticipant");
        }
    }
}
