// <auto-generated />
using System;
using GameOn.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameOn.Persistence.Migrations
{
    [DbContext(typeof(GameOnContext))]
    [Migration("20260724113700_Added_New_Fields_In_LoL_Game")]
    partial class Added_New_Fields_In_LoL_Game
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameOn.Domain.Changelog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("context");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string>("NewFeatures")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("new_features");

                    b.Property<DateTime>("PublicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("publication_date");

                    b.Property<bool>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("published");

                    b.PrimitiveCollection<string>("RemovedFeatures")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("removed_features");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.PrimitiveCollection<string>("UpdatedFeatures")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("updated_features");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("Changelog", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.FifaGamePlayed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("bit")
                        .HasColumnName("is_played");

                    b.Property<int?>("Phase")
                        .HasColumnType("int")
                        .HasColumnName("phase");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    b.Property<DateTime>("PlayedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("played_on");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<int>("Team1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("team_1_id");

                    b.Property<int>("Team2Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("team_2_id");

                    b.Property<int>("TeamScore1")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("team_score_1");

                    b.Property<int>("TeamScore2")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("team_score_2");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PlatformId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("FifaGamePlayed", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.FifaTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("FifaTeam", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.FifaTeamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FifaGameId")
                        .HasColumnType("int")
                        .HasColumnName("fifa_game_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("Team")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("team");

                    b.HasKey("Id");

                    b.HasIndex("FifaGameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("FifaTeamPlayer", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("external_url");

                    b.Property<int>("FifaGameId")
                        .HasColumnType("int")
                        .HasColumnName("fifa_game_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FifaGameId");

                    b.ToTable("Highlight", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LeagueOfLegendsRankHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("created_on");

                    b.Property<bool>("FreshBlood")
                        .HasColumnType("bit")
                        .HasColumnName("fresh_blood");

                    b.Property<bool>("HotStreak")
                        .HasColumnType("bit")
                        .HasColumnName("hot_streak");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit")
                        .HasColumnName("inactive");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("int")
                        .HasColumnName("league_points");

                    b.Property<int>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("queue_type");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("rank");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tier");

                    b.Property<bool>("Veteran")
                        .HasColumnType("bit")
                        .HasColumnName("veteran");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("LeagueOfLegendsRankHistory", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLGame", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("match_id");

                    b.Property<string>("EndOfGameResult")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("end_of_game_result");

                    b.Property<long?>("FrameInterval")
                        .HasColumnType("bigint")
                        .HasColumnName("frame_interval");

                    b.Property<DateTime>("GameEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("game_end");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<DateTime>("GameStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("game_start");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("game_version");

                    b.Property<bool>("IsRemake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_remake");

                    b.Property<int?>("QueueId")
                        .HasColumnType("int")
                        .HasColumnName("queue_id");

                    b.Property<DateTime>("RetrievedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("retrieved_on");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("int")
                        .HasColumnName("winning_team_id");

                    b.HasKey("MatchId");

                    b.HasIndex("QueueId");

                    b.ToTable("LeagueOfLegendsGame", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllInPings")
                        .HasColumnType("int");

                    b.Property<int>("AssistMePings")
                        .HasColumnType("int");

                    b.Property<int>("Assists")
                        .HasColumnType("int")
                        .HasColumnName("assists");

                    b.Property<int>("BaronKills")
                        .HasColumnType("int");

                    b.Property<int>("BountyLevel")
                        .HasColumnType("int");

                    b.Property<int>("ChampExperience")
                        .HasColumnType("int");

                    b.Property<int>("ChampLevel")
                        .HasColumnType("int")
                        .HasColumnName("champLevel");

                    b.Property<int>("ChampionId")
                        .HasColumnType("int")
                        .HasColumnName("champion_id");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("champion_name");

                    b.Property<int>("ChampionTransform")
                        .HasColumnType("int");

                    b.Property<int>("CommandPings")
                        .HasColumnType("int");

                    b.Property<int>("ConsumablesPurchased")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasColumnName("deaths");

                    b.Property<bool>("GameEndedInEarlySurrender")
                        .HasColumnType("bit");

                    b.Property<string>("IndividualPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Item0")
                        .HasColumnType("int")
                        .HasColumnName("item0");

                    b.Property<int>("Item1")
                        .HasColumnType("int")
                        .HasColumnName("item1");

                    b.Property<int>("Item2")
                        .HasColumnType("int")
                        .HasColumnName("item2");

                    b.Property<int>("Item3")
                        .HasColumnType("int")
                        .HasColumnName("item3");

                    b.Property<int>("Item4")
                        .HasColumnType("int")
                        .HasColumnName("item4");

                    b.Property<int>("Item5")
                        .HasColumnType("int")
                        .HasColumnName("item5");

                    b.Property<int>("Item6")
                        .HasColumnType("int")
                        .HasColumnName("item6");

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasColumnName("kills");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("puuid");

                    b.Property<string>("RiotIdGameName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("riot_id_game_name");

                    b.Property<string>("RiotIdTagLine")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("riot_id_tagline");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisionScore")
                        .HasColumnType("int");

                    b.Property<bool>("Win")
                        .HasColumnType("bit")
                        .HasColumnName("win");

                    b.HasKey("Id");

                    b.HasAlternateKey("MatchId", "Puuid")
                        .HasName("AK_LoLGameParticipant_MatchId_Puuid");

                    b.HasIndex("PlayerId");

                    b.ToTable("LeagueOfLegendsGameParticipant", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameParticipantChallenge", b =>
                {
                    b.Property<int>("LoLGameParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("lol_game_participant_id");

                    b.Property<int>("AbilityUses")
                        .HasColumnType("int")
                        .HasColumnName("ability_uses");

                    b.Property<int>("AcesBefore15Minutes")
                        .HasColumnType("int")
                        .HasColumnName("aces_before_15_minutes");

                    b.Property<float>("AlliedJungleMonsterKills")
                        .HasColumnType("real")
                        .HasColumnName("allied_jungle_monster_kills");

                    b.Property<int>("BaronBuffGoldAdvantageOverThreshold")
                        .HasColumnType("int")
                        .HasColumnName("baron_buff_gold_advantage_over_threshold");

                    b.Property<int>("BaronTakedowns")
                        .HasColumnType("int")
                        .HasColumnName("baron_takedowns");

                    b.Property<int>("BlastConeOppositeOpponentCount")
                        .HasColumnType("int")
                        .HasColumnName("blast_cone_opposite_opponent_count");

                    b.Property<int>("BountyGold")
                        .HasColumnType("int")
                        .HasColumnName("bounty_gold");

                    b.Property<int>("BuffsStolen")
                        .HasColumnType("int")
                        .HasColumnName("buffs_stolen");

                    b.Property<int>("CompleteSupportQuestInTime")
                        .HasColumnType("int")
                        .HasColumnName("complete_support_quest_in_time");

                    b.Property<float>("ControlWardTimeCoverageInRiverOrEnemyHalf")
                        .HasColumnType("real")
                        .HasColumnName("control_ward_time_coverage_in_river_or_enemy_half");

                    b.Property<int>("ControlWardsPlaced")
                        .HasColumnType("int")
                        .HasColumnName("control_wards_placed");

                    b.Property<float>("DamagePerMinute")
                        .HasColumnType("real")
                        .HasColumnName("damage_per_minute");

                    b.Property<float>("DamageTakenOnTeamPercentage")
                        .HasColumnType("real")
                        .HasColumnName("damage_taken_on_team_percentage");

                    b.Property<int>("DancedWithRiftHerald")
                        .HasColumnType("int")
                        .HasColumnName("danced_with_rift_herald");

                    b.Property<int>("DeathsByEnemyChamps")
                        .HasColumnType("int")
                        .HasColumnName("deaths_by_enemy_champs");

                    b.Property<int>("DodgeSkillShotsSmallWindow")
                        .HasColumnType("int")
                        .HasColumnName("dodge_skill_shots_small_window");

                    b.Property<int>("DoubleAces")
                        .HasColumnType("int")
                        .HasColumnName("double_aces");

                    b.Property<int>("DragonTakedowns")
                        .HasColumnType("int")
                        .HasColumnName("dragon_takedowns");

                    b.Property<int>("EarliestBaron")
                        .HasColumnType("int")
                        .HasColumnName("earliest_baron");

                    b.Property<int>("EarliestDragonTakedown")
                        .HasColumnType("int")
                        .HasColumnName("earliest_dragon_takedown");

                    b.Property<int>("EarliestElderDragon")
                        .HasColumnType("int")
                        .HasColumnName("earliest_elder_dragon");

                    b.Property<int>("EarlyLaningPhaseGoldExpAdvantage")
                        .HasColumnType("int")
                        .HasColumnName("early_laning_phase_gold_exp_advantage");

                    b.Property<float>("EffectiveHealAndShielding")
                        .HasColumnType("real")
                        .HasColumnName("effective_heal_and_shielding");

                    b.Property<int>("ElderDragonKillsWithOpposingSoul")
                        .HasColumnType("int")
                        .HasColumnName("elder_dragon_kills_with_opposing_soul");

                    b.Property<int>("ElderDragonMultikills")
                        .HasColumnType("int")
                        .HasColumnName("elder_dragon_multikills");

                    b.Property<int>("EnemyChampionImmobilizations")
                        .HasColumnType("int")
                        .HasColumnName("enemy_champion_immobilizations");

                    b.Property<float>("EnemyJungleMonsterKills")
                        .HasColumnType("real")
                        .HasColumnName("enemy_jungle_monster_kills");

                    b.Property<int>("EpicMonsterKillsNearEnemyJungler")
                        .HasColumnType("int")
                        .HasColumnName("epic_monster_kills_near_enemy_jungler");

                    b.Property<int>("EpicMonsterKillsWithin30SecondsOfSpawn")
                        .HasColumnType("int")
                        .HasColumnName("epic_monster_kills_within_30_seconds_of_spawn");

                    b.Property<int>("EpicMonsterSteals")
                        .HasColumnType("int")
                        .HasColumnName("epic_monster_steals");

                    b.Property<int>("EpicMonsterStolenWithoutSmite")
                        .HasColumnType("int")
                        .HasColumnName("epic_monster_stolen_without_smite");

                    b.Property<int>("FasterSupportQuestCompletion")
                        .HasColumnType("int")
                        .HasColumnName("faster_support_quest_completion");

                    b.Property<int>("FastestLegendary")
                        .HasColumnType("int")
                        .HasColumnName("fastest_legendary");

                    b.Property<int>("FistBumpParticipation")
                        .HasColumnType("int")
                        .HasColumnName("fist_bump_participation");

                    b.Property<int>("FlawlessAces")
                        .HasColumnType("int")
                        .HasColumnName("flawless_aces");

                    b.Property<int>("FullTeamTakedown")
                        .HasColumnType("int")
                        .HasColumnName("full_team_takedown");

                    b.Property<float>("GameLength")
                        .HasColumnType("real")
                        .HasColumnName("game_length");

                    b.Property<float>("GoldPerMinute")
                        .HasColumnType("real")
                        .HasColumnName("gold_per_minute");

                    b.Property<int>("HadAfkTeammate")
                        .HasColumnType("int")
                        .HasColumnName("had_afk_teammate");

                    b.Property<int>("HadOpenNexus")
                        .HasColumnType("int")
                        .HasColumnName("had_open_nexus");

                    b.Property<int>("HighestChampionDamage")
                        .HasColumnType("int")
                        .HasColumnName("highest_champion_damage");

                    b.Property<int>("HighestCrowdControlScore")
                        .HasColumnType("int")
                        .HasColumnName("highest_crowd_control_score");

                    b.Property<int>("HighestWardKills")
                        .HasColumnType("int")
                        .HasColumnName("highest_ward_kills");

                    b.Property<int>("ImmobilizeAndKillWithAlly")
                        .HasColumnType("int")
                        .HasColumnName("immobilize_and_kill_with_ally");

                    b.Property<int>("InfernalScalePickup")
                        .HasColumnType("int")
                        .HasColumnName("infernal_scale_pickup");

                    b.Property<float>("JungleCsBefore10Minutes")
                        .HasColumnType("real")
                        .HasColumnName("jungle_cs_before_10_minutes");

                    b.Property<int>("JunglerKillsEarlyJungle")
                        .HasColumnType("int")
                        .HasColumnName("jungler_kills_early_jungle");

                    b.Property<int>("JunglerTakedownsNearDamagedEpicMonster")
                        .HasColumnType("int")
                        .HasColumnName("jungler_takedowns_near_damaged_epic_monster");

                    b.Property<int>("KTurretsDestroyedBeforePlatesFall")
                        .HasColumnType("int")
                        .HasColumnName("k_turrets_destroyed_before_plates_fall");

                    b.Property<float>("Kda")
                        .HasColumnType("real")
                        .HasColumnName("kda");

                    b.Property<int>("KillAfterHiddenWithAlly")
                        .HasColumnType("int")
                        .HasColumnName("kill_after_hidden_with_ally");

                    b.Property<float>("KillParticipation")
                        .HasColumnType("real")
                        .HasColumnName("kill_participation");

                    b.Property<int>("KillsNearEnemyTurret")
                        .HasColumnType("int")
                        .HasColumnName("kills_near_enemy_turret");

                    b.Property<int>("KillsOnLanersEarlyJungleAsJungler")
                        .HasColumnType("int")
                        .HasColumnName("kills_on_laners_early_jungle_as_jungler");

                    b.Property<int>("KillsOnOtherLanesEarlyJungleAsLaner")
                        .HasColumnType("int")
                        .HasColumnName("kills_on_other_lanes_early_jungle_as_laner");

                    b.Property<int>("KillsUnderOwnTurret")
                        .HasColumnType("int")
                        .HasColumnName("kills_under_own_turret");

                    b.Property<int>("KillsWithHelpFromEpicMonster")
                        .HasColumnType("int")
                        .HasColumnName("kills_with_help_from_epic_monster");

                    b.Property<int>("KnockEnemyIntoTeamAndKill")
                        .HasColumnType("int")
                        .HasColumnName("knock_enemy_into_team_and_kill");

                    b.Property<int>("LandSkillShotsEarlyGame")
                        .HasColumnType("int")
                        .HasColumnName("land_skill_shots_early_game");

                    b.Property<int>("LaneMinionsFirst10Minutes")
                        .HasColumnType("int")
                        .HasColumnName("lane_minions_first_10_minutes");

                    b.Property<int>("LaningPhaseGoldExpAdvantage")
                        .HasColumnType("int")
                        .HasColumnName("laning_phase_gold_exp_advantage");

                    b.Property<int>("LegendaryCount")
                        .HasColumnType("int")
                        .HasColumnName("legendary_count");

                    b.Property<int>("LostAnInhibitor")
                        .HasColumnType("int")
                        .HasColumnName("lost_an_inhibitor");

                    b.Property<float>("MaxCsAdvantageOnLaneOpponent")
                        .HasColumnType("real")
                        .HasColumnName("max_cs_advantage_on_lane_opponent");

                    b.Property<int>("MaxKillDeficit")
                        .HasColumnType("int")
                        .HasColumnName("max_kill_deficit");

                    b.Property<int>("MaxLevelLeadLaneOpponent")
                        .HasColumnType("int")
                        .HasColumnName("max_level_lead_lane_opponent");

                    b.Property<int>("MejaisFullStackInTime")
                        .HasColumnType("int")
                        .HasColumnName("mejais_full_stack_in_time");

                    b.Property<float>("MoreEnemyJungleThanOpponent")
                        .HasColumnType("real")
                        .HasColumnName("more_enemy_jungle_than_opponent");

                    b.Property<int>("MostWardsDestroyedOneSweeper")
                        .HasColumnType("int")
                        .HasColumnName("most_wards_destroyed_one_sweeper");

                    b.Property<int>("MultiKillOneSpell")
                        .HasColumnType("int")
                        .HasColumnName("multi_kill_one_spell");

                    b.Property<int>("MultiTurretRiftHeraldCount")
                        .HasColumnType("int")
                        .HasColumnName("multi_turret_rift_herald_count");

                    b.Property<int>("Multikills")
                        .HasColumnType("int")
                        .HasColumnName("multikills");

                    b.Property<int>("MultikillsAfterAggressiveFlash")
                        .HasColumnType("int")
                        .HasColumnName("multikills_after_aggressive_flash");

                    b.Property<int>("MythicItemUsed")
                        .HasColumnType("int")
                        .HasColumnName("mythic_item_used");

                    b.Property<int>("OneTwoAssistStreakCount")
                        .HasColumnType("int")
                        .HasColumnName("one_two_assist_streak_count");

                    b.Property<int>("OuterTurretExecutesBefore10Minutes")
                        .HasColumnType("int")
                        .HasColumnName("outer_turret_executes_before_10_minutes");

                    b.Property<int>("OutnumberedKills")
                        .HasColumnType("int")
                        .HasColumnName("outnumbered_kills");

                    b.Property<int>("OutnumberedNexusKill")
                        .HasColumnType("int")
                        .HasColumnName("outnumbered_nexus_kill");

                    b.Property<int>("PerfectDragonSoulsTaken")
                        .HasColumnType("int")
                        .HasColumnName("perfect_dragon_souls_taken");

                    b.Property<int>("PerfectGame")
                        .HasColumnType("int")
                        .HasColumnName("perfect_game");

                    b.Property<int>("PickKillWithAlly")
                        .HasColumnType("int")
                        .HasColumnName("pick_kill_with_ally");

                    b.Property<int>("PlayedChampSelectPosition")
                        .HasColumnType("int")
                        .HasColumnName("played_champ_select_position");

                    b.Property<int>("PoroExplosions")
                        .HasColumnType("int")
                        .HasColumnName("poro_explosions");

                    b.Property<int>("QuickCleanse")
                        .HasColumnType("int")
                        .HasColumnName("quick_cleanse");

                    b.Property<int>("QuickFirstTurret")
                        .HasColumnType("int")
                        .HasColumnName("quick_first_turret");

                    b.Property<int>("RiftHeraldTakedowns")
                        .HasColumnType("int")
                        .HasColumnName("rift_herald_takedowns");

                    b.Property<int>("SaveAllyFromDeath")
                        .HasColumnType("int")
                        .HasColumnName("save_ally_from_death");

                    b.Property<int>("ScuttleCrabKills")
                        .HasColumnType("int")
                        .HasColumnName("scuttle_crab_kills");

                    b.Property<int>("SkillshotsDodged")
                        .HasColumnType("int")
                        .HasColumnName("skillshots_dodged");

                    b.Property<int>("SkillshotsHit")
                        .HasColumnType("int")
                        .HasColumnName("skillshots_hit");

                    b.Property<int>("SnowballsHit")
                        .HasColumnType("int")
                        .HasColumnName("snowballs_hit");

                    b.Property<int>("SoloBaronKills")
                        .HasColumnType("int")
                        .HasColumnName("solo_baron_kills");

                    b.Property<int>("SoloKills")
                        .HasColumnType("int")
                        .HasColumnName("solo_kills");

                    b.Property<int>("SoloTurretsLategame")
                        .HasColumnType("int")
                        .HasColumnName("solo_turrets_lategame");

                    b.Property<int>("StealthWardsPlaced")
                        .HasColumnType("int")
                        .HasColumnName("stealth_wards_placed");

                    b.Property<int>("SurvivedSingleDigitHpCount")
                        .HasColumnType("int")
                        .HasColumnName("survived_single_digit_hp_count");

                    b.Property<int>("SurvivedThreeImmobilizesInFight")
                        .HasColumnType("int")
                        .HasColumnName("survived_three_immobilizes_in_fight");

                    b.Property<int>("TakedownOnFirstTurret")
                        .HasColumnType("int")
                        .HasColumnName("takedown_on_first_turret");

                    b.Property<int>("Takedowns")
                        .HasColumnType("int")
                        .HasColumnName("takedowns");

                    b.Property<int>("TakedownsAfterGainingLevelAdvantage")
                        .HasColumnType("int")
                        .HasColumnName("takedowns_after_gaining_level_advantage");

                    b.Property<int>("TakedownsBeforeJungleMinionSpawn")
                        .HasColumnType("int")
                        .HasColumnName("takedowns_before_jungle_minion_spawn");

                    b.Property<int>("TakedownsFirst25Minutes")
                        .HasColumnType("int")
                        .HasColumnName("takedowns_first_25_minutes");

                    b.Property<int>("TakedownsInEnemyFountain")
                        .HasColumnType("int")
                        .HasColumnName("takedowns_in_enemy_fountain");

                    b.Property<int>("TeamBaronKills")
                        .HasColumnType("int")
                        .HasColumnName("team_baron_kills");

                    b.Property<float>("TeamDamagePercentage")
                        .HasColumnType("real")
                        .HasColumnName("team_damage_percentage");

                    b.Property<int>("TeamElderDragonKills")
                        .HasColumnType("int")
                        .HasColumnName("team_elder_dragon_kills");

                    b.Property<int>("TeamRiftHeraldKills")
                        .HasColumnType("int")
                        .HasColumnName("team_rift_herald_kills");

                    b.Property<int>("TeleportTakedowns")
                        .HasColumnType("int")
                        .HasColumnName("teleport_takedowns");

                    b.Property<int>("ThirdInhibitorDestroyedTime")
                        .HasColumnType("int")
                        .HasColumnName("third_inhibitor_destroyed_time");

                    b.Property<int>("ThreeWardsOneSweeperCount")
                        .HasColumnType("int")
                        .HasColumnName("three_wards_one_sweeper_count");

                    b.Property<int>("TookLargeDamageSurvived")
                        .HasColumnType("int")
                        .HasColumnName("took_large_damage_survived");

                    b.Property<int>("TurretPlatesTaken")
                        .HasColumnType("int")
                        .HasColumnName("turret_plates_taken");

                    b.Property<int>("TurretTakedowns")
                        .HasColumnType("int")
                        .HasColumnName("turret_takedowns");

                    b.Property<int>("TurretsTakenWithRiftHerald")
                        .HasColumnType("int")
                        .HasColumnName("turrets_taken_with_rift_herald");

                    b.Property<int>("TwentyMinionsIn3SecondsCount")
                        .HasColumnType("int")
                        .HasColumnName("twenty_minions_in_3_seconds_count");

                    b.Property<int>("UnseenRecalls")
                        .HasColumnType("int")
                        .HasColumnName("unseen_recalls");

                    b.Property<float>("VisionScoreAdvantageLaneOpponent")
                        .HasColumnType("real")
                        .HasColumnName("vision_score_advantage_lane_opponent");

                    b.Property<float>("VisionScorePerMinute")
                        .HasColumnType("real")
                        .HasColumnName("vision_score_per_minute");

                    b.Property<int>("VoidMonsterKill")
                        .HasColumnType("int")
                        .HasColumnName("void_monster_kill");

                    b.Property<int>("WardTakedowns")
                        .HasColumnType("int")
                        .HasColumnName("ward_takedowns");

                    b.Property<int>("WardTakedownsBefore20M")
                        .HasColumnType("int")
                        .HasColumnName("ward_takedowns_before_20m");

                    b.Property<int>("WardsGuarded")
                        .HasColumnType("int")
                        .HasColumnName("wards_guarded");

                    b.HasKey("LoLGameParticipantId");

                    b.ToTable("LeagueOfLegendsGameParticipantChallenge", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameParticipantStat", b =>
                {
                    b.Property<int>("LoLGameParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("lol_game_participant_id");

                    b.Property<DateTime>("ComputedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("computed_on");

                    b.Property<int>("CreepScore")
                        .HasColumnType("int")
                        .HasColumnName("creep_score");

                    b.Property<double>("CsPerMinute")
                        .HasColumnType("float")
                        .HasColumnName("cs_per_minute");

                    b.Property<int>("DamageDealtToChampions")
                        .HasColumnType("int")
                        .HasColumnName("damage_dealt_to_champions");

                    b.Property<double>("DamagePerMinute")
                        .HasColumnType("float")
                        .HasColumnName("damage_per_minute");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("int")
                        .HasColumnName("damage_taken");

                    b.Property<int>("GameDurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("game_duration_seconds");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("int")
                        .HasColumnName("gold_earned");

                    b.Property<double>("GoldPerMinute")
                        .HasColumnType("float")
                        .HasColumnName("gold_per_minute");

                    b.Property<double>("Kda")
                        .HasColumnType("float")
                        .HasColumnName("kda");

                    b.Property<double>("KillParticipationPercent")
                        .HasColumnType("float")
                        .HasColumnName("kill_participation_percent");

                    b.Property<int>("WardsKilled")
                        .HasColumnType("int")
                        .HasColumnName("wards_killed");

                    b.Property<int>("WardsPlaced")
                        .HasColumnType("int")
                        .HasColumnName("wards_placed");

                    b.HasKey("LoLGameParticipantId");

                    b.ToTable("LeagueOfLegendsGameParticipantStat", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AfterId")
                        .HasColumnType("int")
                        .HasColumnName("after_id");

                    b.Property<int?>("BeforeId")
                        .HasColumnType("int")
                        .HasColumnName("before_id");

                    b.Property<int?>("Bounty")
                        .HasColumnType("int")
                        .HasColumnName("bounty");

                    b.Property<string>("BuildingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("building_type");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("creator_id");

                    b.Property<string>("CreatorPUUID")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("creator_puuid");

                    b.Property<string>("DragonSoulType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("dragon_soul_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("event_type");

                    b.Property<int?>("GoldGain")
                        .HasColumnType("int")
                        .HasColumnName("gold_gain");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int?>("KillStreakLength")
                        .HasColumnType("int")
                        .HasColumnName("kill_streak_length");

                    b.Property<string>("KillType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("kill_type");

                    b.Property<int?>("KillerId")
                        .HasColumnType("int")
                        .HasColumnName("killer_id");

                    b.Property<string>("KillerPUUID")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("killer_puuid");

                    b.Property<int?>("KillerTeamId")
                        .HasColumnType("int")
                        .HasColumnName("killer_team_id");

                    b.Property<string>("LaneType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lane_type");

                    b.Property<int?>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("LevelUpType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("level_up_type");

                    b.Property<int>("LoLGameTimelineFrameId")
                        .HasColumnType("int")
                        .HasColumnName("timeline_frame_id");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("match_id");

                    b.Property<string>("MonsterSubType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("monster_sub_type");

                    b.Property<string>("MonsterType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("monster_type");

                    b.Property<int?>("MultiKillLength")
                        .HasColumnType("int")
                        .HasColumnName("multi_kill_length");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantPUUID")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("participant_puuid");

                    b.Property<int?>("PositionX")
                        .HasColumnType("int")
                        .HasColumnName("position_x");

                    b.Property<int?>("PositionY")
                        .HasColumnType("int")
                        .HasColumnName("position_y");

                    b.Property<long?>("RealTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("real_timestamp");

                    b.Property<int?>("ShutdownBounty")
                        .HasColumnType("int")
                        .HasColumnName("shutdown_bounty");

                    b.Property<int?>("SkillSlot")
                        .HasColumnType("int")
                        .HasColumnName("skill_slot");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int>("Timestamp")
                        .HasColumnType("int")
                        .HasColumnName("timestamp");

                    b.Property<string>("TowerType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tower_type");

                    b.Property<string>("TransformType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transform_type");

                    b.Property<int?>("VictimId")
                        .HasColumnType("int")
                        .HasColumnName("victim_id");

                    b.Property<string>("VictimPUUID")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("victim_puuid");

                    b.Property<string>("WardType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ward_type");

                    b.HasKey("Id");

                    b.HasIndex("LoLGameTimelineFrameId");

                    b.HasIndex("MatchId", "CreatorPUUID");

                    b.HasIndex("MatchId", "KillerPUUID");

                    b.HasIndex("MatchId", "ParticipantPUUID");

                    b.HasIndex("MatchId", "VictimPUUID");

                    b.ToTable("LeagueOfLegendsGameTimelineEvent", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineEventAssist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoLGameTimelineEventId")
                        .HasColumnType("int")
                        .HasColumnName("timeline_event_id");

                    b.Property<string>("MatchId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("match_id");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<string>("ParticipantPUUID")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("participant_puuid");

                    b.HasKey("Id");

                    b.HasIndex("LoLGameTimelineEventId");

                    b.HasIndex("MatchId", "ParticipantPUUID");

                    b.ToTable("LeagueOfLegendsGameTimelineEventAssist", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("match_id");

                    b.Property<int>("Timestamp")
                        .HasColumnType("int")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("LeagueOfLegendsGameTimelineFrame", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineFrameParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityHaste")
                        .HasColumnType("int")
                        .HasColumnName("ability_haste");

                    b.Property<int>("AbilityPower")
                        .HasColumnType("int")
                        .HasColumnName("ability_power");

                    b.Property<int>("Armor")
                        .HasColumnType("int")
                        .HasColumnName("armor");

                    b.Property<int>("ArmorPen")
                        .HasColumnType("int")
                        .HasColumnName("armor_pen");

                    b.Property<int>("ArmorPenPercent")
                        .HasColumnType("int")
                        .HasColumnName("armor_pen_percent");

                    b.Property<int>("AttackDamage")
                        .HasColumnType("int")
                        .HasColumnName("attack_damage");

                    b.Property<int>("AttackSpeed")
                        .HasColumnType("int")
                        .HasColumnName("attack_speed");

                    b.Property<int>("BonusArmorPenPercent")
                        .HasColumnType("int")
                        .HasColumnName("bonus_armor_pen_percent");

                    b.Property<int>("BonusMagicPenPercent")
                        .HasColumnType("int")
                        .HasColumnName("bonus_magic_pen_percent");

                    b.Property<int>("CcReduction")
                        .HasColumnType("int")
                        .HasColumnName("cc_reduction");

                    b.Property<int>("CooldownReduction")
                        .HasColumnType("int")
                        .HasColumnName("cooldown_reduction");

                    b.Property<int>("CurrentGold")
                        .HasColumnType("int")
                        .HasColumnName("current_gold");

                    b.Property<int>("GoldPerSecond")
                        .HasColumnType("int")
                        .HasColumnName("gold_per_second");

                    b.Property<int>("Health")
                        .HasColumnType("int")
                        .HasColumnName("health");

                    b.Property<int>("HealthMax")
                        .HasColumnType("int")
                        .HasColumnName("health_max");

                    b.Property<int>("HealthRegen")
                        .HasColumnType("int")
                        .HasColumnName("health_regen");

                    b.Property<int>("JungleMinionsKilled")
                        .HasColumnType("int")
                        .HasColumnName("jungle_minions_killed");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("Lifesteal")
                        .HasColumnType("int")
                        .HasColumnName("lifesteal");

                    b.Property<int>("LoLGameTimelineFrameId")
                        .HasColumnType("int")
                        .HasColumnName("timeline_frame_id");

                    b.Property<int>("MagicDamageDone")
                        .HasColumnType("int")
                        .HasColumnName("magic_damage_done");

                    b.Property<int>("MagicDamageDoneToChampions")
                        .HasColumnType("int")
                        .HasColumnName("magic_damage_done_to_champions");

                    b.Property<int>("MagicDamageTaken")
                        .HasColumnType("int")
                        .HasColumnName("magic_damage_taken");

                    b.Property<int>("MagicPen")
                        .HasColumnType("int")
                        .HasColumnName("magic_pen");

                    b.Property<int>("MagicPenPercent")
                        .HasColumnType("int")
                        .HasColumnName("magic_pen_percent");

                    b.Property<int>("MagicResist")
                        .HasColumnType("int")
                        .HasColumnName("magic_resist");

                    b.Property<int>("MinionsKilled")
                        .HasColumnType("int")
                        .HasColumnName("minions_killed");

                    b.Property<int>("MovementSpeed")
                        .HasColumnType("int")
                        .HasColumnName("movement_speed");

                    b.Property<int>("Omnivamp")
                        .HasColumnType("int")
                        .HasColumnName("omnivamp");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participantId");

                    b.Property<string>("ParticipantPUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("participantPuuid");

                    b.Property<int>("PhysicalDamageDone")
                        .HasColumnType("int")
                        .HasColumnName("physical_damage_done");

                    b.Property<int>("PhysicalDamageDoneToChampions")
                        .HasColumnType("int")
                        .HasColumnName("physical_damage_done_to_champions");

                    b.Property<int>("PhysicalDamageTaken")
                        .HasColumnType("int")
                        .HasColumnName("physical_damage_taken");

                    b.Property<int>("PhysicalVamp")
                        .HasColumnType("int")
                        .HasColumnName("physical_vamp");

                    b.Property<int>("PositionX")
                        .HasColumnType("int")
                        .HasColumnName("position_x");

                    b.Property<int>("PositionY")
                        .HasColumnType("int")
                        .HasColumnName("position_y");

                    b.Property<int>("Power")
                        .HasColumnType("int")
                        .HasColumnName("power");

                    b.Property<int>("PowerMax")
                        .HasColumnType("int")
                        .HasColumnName("power_max");

                    b.Property<int>("PowerRegen")
                        .HasColumnType("int")
                        .HasColumnName("power_regen");

                    b.Property<int>("SpellVamp")
                        .HasColumnType("int")
                        .HasColumnName("spell_vamp");

                    b.Property<int>("TimeEnemySpentControlled")
                        .HasColumnType("int")
                        .HasColumnName("time_enemy_spent_controlled");

                    b.Property<int>("TotalDamageDone")
                        .HasColumnType("int")
                        .HasColumnName("total_damage_done");

                    b.Property<int>("TotalDamageDoneToChampions")
                        .HasColumnType("int")
                        .HasColumnName("total_damage_done_to_champions");

                    b.Property<int>("TotalDamageTaken")
                        .HasColumnType("int")
                        .HasColumnName("total_damage_taken");

                    b.Property<int>("TotalGold")
                        .HasColumnType("int")
                        .HasColumnName("total_gold");

                    b.Property<int>("TrueDamageDone")
                        .HasColumnType("int")
                        .HasColumnName("true_damage_done");

                    b.Property<int>("TrueDamageDoneToChampions")
                        .HasColumnType("int")
                        .HasColumnName("true_damage_done_to_champions");

                    b.Property<int>("TrueDamageTaken")
                        .HasColumnType("int")
                        .HasColumnName("true_damage_taken");

                    b.Property<int>("Xp")
                        .HasColumnType("int")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("LoLGameTimelineFrameId");

                    b.ToTable("LeagueOfLegendsGameTimelineFrameParticipant", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.LoLQueue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("map");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.ToTable("LeagueOfLegendsQueue", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Platform", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("archived");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("created_on");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("KeycloakId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("keycloak_id");

                    b.Property<int?>("LolIconId")
                        .HasColumnType("int")
                        .HasColumnName("lol_icon_id");

                    b.Property<DateTime?>("LolRefreshedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("lol_refreshed_on");

                    b.Property<long?>("LolSummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("RiotGamesNickname")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("riot_games_nickname");

                    b.Property<string>("RiotGamesPUUID")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("riot_games_puuid");

                    b.Property<string>("RiotGamesTagLine")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("riot_games_tag_line");

                    b.HasKey("Id");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DrawPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("draw_points");

                    b.Property<bool>("Featured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("featured");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("logo_url");

                    b.Property<int>("LoosePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("loose_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phase2ChallongeUrl")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("phase2_challonge_url");

                    b.Property<bool>("PhaseOneDoubleRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("phase_one_double_round");

                    b.Property<DateTime>("PlannedFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("planned_from");

                    b.Property<DateTime>("PlannedTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("planned_to");

                    b.Property<string>("Rules")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rules");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("state");

                    b.Property<int>("WinPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("win_points");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Tournament", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.TournamentPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FifaTeamId")
                        .HasColumnType("int")
                        .HasColumnName("fifa_team_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("joined_at");

                    b.Property<int?>("Phase1Score")
                        .HasColumnType("int")
                        .HasColumnName("phase_1_score");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("FifaTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPlayer", (string)null);
                });

            modelBuilder.Entity("GameOn.Domain.FifaGamePlayed", b =>
                {
                    b.HasOne("GameOn.Domain.Player", "CreatedBy")
                        .WithMany("FifaGameCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FifaGamePlayed_Player_Created_By");

                    b.HasOne("GameOn.Domain.Platform", "Platform")
                        .WithMany("GamesPlayed")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FifaGamePlayed_Platform");

                    b.HasOne("GameOn.Domain.Season", "Season")
                        .WithMany("FifaGamePlayed")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FifaGamePlayed_Season");

                    b.HasOne("GameOn.Domain.FifaTeam", "Team1")
                        .WithMany("GamesPlayedTeam1")
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FifaGamePlayed_FifaTeam1");

                    b.HasOne("GameOn.Domain.FifaTeam", "Team2")
                        .WithMany("GamesPlayedTeam2")
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FifaGamePlayed_FifaTeam2");

                    b.HasOne("GameOn.Domain.Tournament", "Tournament")
                        .WithMany("Games")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_FifaGamePlayed_Tournament");

                    b.Navigation("CreatedBy");

                    b.Navigation("Platform");

                    b.Navigation("Season");

                    b.Navigation("Team1");

                    b.Navigation("Team2");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("GameOn.Domain.FifaTeamPlayer", b =>
                {
                    b.HasOne("GameOn.Domain.FifaGamePlayed", "FifaGamePlayed")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("FifaGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FifaTeamPlayer_FifaGamePlayed");

                    b.HasOne("GameOn.Domain.Player", "Player")
                        .WithMany("FifaTeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FifaTeamPlayer_Player");

                    b.Navigation("FifaGamePlayed");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameOn.Domain.Highlight", b =>
                {
                    b.HasOne("GameOn.Domain.Player", "CreatedBy")
                        .WithMany("Highlights")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Highlight_Player_Created_By");

                    b.HasOne("GameOn.Domain.FifaGamePlayed", "FifaGame")
                        .WithMany("Highlights")
                        .HasForeignKey("FifaGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FifaGame_Highlight");

                    b.Navigation("CreatedBy");

                    b.Navigation("FifaGame");
                });

            modelBuilder.Entity("GameOn.Domain.LeagueOfLegendsRankHistory", b =>
                {
                    b.HasOne("GameOn.Domain.Player", "Player")
                        .WithMany("LeagueOfLegendsRankHistory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Player_LoLRankHistory");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGame", b =>
                {
                    b.HasOne("GameOn.Domain.LoLQueue", "Queue")
                        .WithMany("LeagueOfLegendsGames")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_LoLGame_LoLQueue");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameParticipant", b =>
                {
                    b.HasOne("GameOn.Domain.LoLGame", "Game")
                        .WithMany("LeagueOfLegendsGameParticipants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoL_Games_Participants");

                    b.HasOne("GameOn.Domain.Player", "Player")
                        .WithMany("LeagueOfLegendsGameParticipants")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Player_LoL_Game_Participant");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameParticipantChallenge", b =>
                {
                    b.HasOne("GameOn.Domain.LoLGameParticipant", "Participant")
                        .WithOne("Challenges")
                        .HasForeignKey("GameOn.Domain.LoLGameParticipantChallenge", "LoLGameParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoL_Game_Participant_Challenge");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameParticipantStat", b =>
                {
                    b.HasOne("GameOn.Domain.LoLGameParticipant", "Participant")
                        .WithOne("Stats")
                        .HasForeignKey("GameOn.Domain.LoLGameParticipantStat", "LoLGameParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoL_Game_Participant_Stat");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineEvent", b =>
                {
                    b.HasOne("GameOn.Domain.LoLGameTimelineFrame", "TimelineFrame")
                        .WithMany("LoLGameTimelineEvents")
                        .HasForeignKey("LoLGameTimelineFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoL_Game_Frame_Event");

                    b.HasOne("GameOn.Domain.LoLGameParticipant", "Creator")
                        .WithMany()
                        .HasForeignKey("MatchId", "CreatorPUUID")
                        .HasPrincipalKey("MatchId", "Puuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LoL_Event_Creator");

                    b.HasOne("GameOn.Domain.LoLGameParticipant", "Killer")
                        .WithMany()
                        .HasForeignKey("MatchId", "KillerPUUID")
                        .HasPrincipalKey("MatchId", "Puuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LoL_Event_Killer");

                    b.HasOne("GameOn.Domain.LoLGameParticipant", "Participant")
                        .WithMany()
                        .HasForeignKey("MatchId", "ParticipantPUUID")
                        .HasPrincipalKey("MatchId", "Puuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LoL_Event_Participant");

                    b.HasOne("GameOn.Domain.LoLGameParticipant", "Victim")
                        .WithMany()
                        .HasForeignKey("MatchId", "VictimPUUID")
                        .HasPrincipalKey("MatchId", "Puuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LoL_Event_Victim");

                    b.Navigation("Creator");

                    b.Navigation("Killer");

                    b.Navigation("Participant");

                    b.Navigation("TimelineFrame");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineEventAssist", b =>
                {
                    b.HasOne("GameOn.Domain.LoLGameTimelineEvent", "Event")
                        .WithMany("LoLGameTimelineEventAssists")
                        .HasForeignKey("LoLGameTimelineEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoL_Game_Event_Assist");

                    b.HasOne("GameOn.Domain.LoLGameParticipant", "Participant")
                        .WithMany()
                        .HasForeignKey("MatchId", "ParticipantPUUID")
                        .HasPrincipalKey("MatchId", "Puuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LoL_EventAssist_Participant");

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineFrame", b =>
                {
                    b.HasOne("GameOn.Domain.LoLGame", "Game")
                        .WithMany("LoLGameTimelineFrames")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoL_Game_Frame");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineFrameParticipant", b =>
                {
                    b.HasOne("GameOn.Domain.LoLGameTimelineFrame", "TimelineFrame")
                        .WithMany("LoLGameTimelineFrameParticipants")
                        .HasForeignKey("LoLGameTimelineFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoL_Game_Frame_Participant");

                    b.Navigation("TimelineFrame");
                });

            modelBuilder.Entity("GameOn.Domain.Tournament", b =>
                {
                    b.HasOne("GameOn.Domain.Player", "Winner")
                        .WithMany("TournamentsWon")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Tournament_Player_Winner");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GameOn.Domain.TournamentPlayer", b =>
                {
                    b.HasOne("GameOn.Domain.FifaTeam", "FifaTeam")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("FifaTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TournamentPlayer_FifaTeam");

                    b.HasOne("GameOn.Domain.Player", "Player")
                        .WithMany("TournamentPlayed")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TournamentPlayer_Player");

                    b.HasOne("GameOn.Domain.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TournamentPlayer_Tournament");

                    b.Navigation("FifaTeam");

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("GameOn.Domain.FifaGamePlayed", b =>
                {
                    b.Navigation("Highlights");

                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("GameOn.Domain.FifaTeam", b =>
                {
                    b.Navigation("GamesPlayedTeam1");

                    b.Navigation("GamesPlayedTeam2");

                    b.Navigation("TournamentPlayers");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGame", b =>
                {
                    b.Navigation("LeagueOfLegendsGameParticipants");

                    b.Navigation("LoLGameTimelineFrames");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameParticipant", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineEvent", b =>
                {
                    b.Navigation("LoLGameTimelineEventAssists");
                });

            modelBuilder.Entity("GameOn.Domain.LoLGameTimelineFrame", b =>
                {
                    b.Navigation("LoLGameTimelineEvents");

                    b.Navigation("LoLGameTimelineFrameParticipants");
                });

            modelBuilder.Entity("GameOn.Domain.LoLQueue", b =>
                {
                    b.Navigation("LeagueOfLegendsGames");
                });

            modelBuilder.Entity("GameOn.Domain.Platform", b =>
                {
                    b.Navigation("GamesPlayed");
                });

            modelBuilder.Entity("GameOn.Domain.Player", b =>
                {
                    b.Navigation("FifaGameCreated");

                    b.Navigation("FifaTeamPlayers");

                    b.Navigation("Highlights");

                    b.Navigation("LeagueOfLegendsGameParticipants");

                    b.Navigation("LeagueOfLegendsRankHistory");

                    b.Navigation("TournamentPlayed");

                    b.Navigation("TournamentsWon");
                });

            modelBuilder.Entity("GameOn.Domain.Season", b =>
                {
                    b.Navigation("FifaGamePlayed");
                });

            modelBuilder.Entity("GameOn.Domain.Tournament", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
