// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameOn.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Added_LoLGameParticipantRankChange : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "LeagueOfLegendsGameParticipantRankChange",
                columns: table => new
                {
                    lol_game_participant_id = table.Column<int>(type: "int", nullable: false),
                    league_points_change = table.Column<int>(type: "int", nullable: false),
                    tier_before = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    rank_before = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    league_points_before = table.Column<int>(type: "int", nullable: false),
                    tier_after = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    rank_after = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    league_points_after = table.Column<int>(type: "int", nullable: false),
                    computed_on = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LeagueOfLegendsGameParticipantRankChange", x => x.lol_game_participant_id);
                    table.ForeignKey(
                        name: "FK_LoL_Game_Participant_Rank_Change",
                        column: x => x.lol_game_participant_id,
                        principalTable: "LeagueOfLegendsGameParticipant",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "LeagueOfLegendsGameParticipantRankChange");
        }
    }
}
